# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
      # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: server
    main: ./cmd/server/server.go
    binary: server
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

  - id: termishare
    main: ./cmd/termishare/termishare.go
    binary: termishare
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - id: server
    builds:
      - server
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: termishare
    builds:
      - termishare
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
