# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termishare < Formula
  desc "Peer to peer terminal sharing"
  homepage "https://github.com/qnkhuat/termishare"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.3/termishare_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "5a405badabba9872b0f5c97371d3aaf50c189452ff76218ce4758fb852d912a2"

      def install
        bin.install "termishare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.3/termishare_0.0.3_Darwin_arm64.tar.gz"
      sha256 "09372e5997a1a3507341d27a62bd129368671a7451bc84127c110b937ae1b180"

      def install
        bin.install "termishare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.3/termishare_0.0.3_Linux_arm64.tar.gz"
      sha256 "0e847c9b8edbb0e9d0e4aefb452e898e3e1d6ef8be02117eb6ab8073fb60db70"

      def install
        bin.install "termishare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.3/termishare_0.0.3_Linux_x86_64.tar.gz"
      sha256 "48d9e0235ca160b305e8dbba354b6acc2916f8458e5c410e6b98fa10432e0c94"

      def install
        bin.install "termishare"
      end
    end
  end
end
