name: uberjar

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  uberjar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: www
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.933.sh &&
          sudo bash ./linux-install-1.10.3.933.sh

      - name: Get node_modules cache
        uses: actions/cache@v2
        with:
          path: www/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Get M2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}

      - name: Check versions
        run: |
          echo "Node.js `node --version`"
          echo "yarn `yarn --version`"
          java -version

      - name: Build
        run: clojure -T:build uber

      - name: Release
        uses: softprops/action-gh-release@v1
        # currently action-gh-release doesn't recognize working-directory from defaults
        with:
          files: www/target/termishare.jar
