name: uberjar

on:
  pull_request:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'cli/**'

jobs:
  uberjar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: www
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Prepare JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.933.sh &&
          sudo bash ./linux-install-1.10.3.933.sh
      - name: Check versions
        run: |
          echo "Node.js `node --version`"
          echo "yarn `yarn --version`"
          java -version
     - name: Build
       run: clj -T:build uber
